name: medical_app
description: A medical records Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
